version: '3'
services:
  odoo:
    container_name: odoo110
    build:
      context: .
    network_mode: host
    volumes: 
#     - $HOME/.ssh/id_rsa:/opt/.ssh/id_rsa
     - $HOME/.local/share/Odoo:/opt/.local/share/Odoo
#    restart: always 
# this restart policy should be used only after image is okay, otherwise it creates huge problem 
#starting again and again not letting new changes refelect

